# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1050, 871)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblDisplayedEcho = QtGui.QLabel(self.tab)
        self.lblDisplayedEcho.setObjectName(_fromUtf8("lblDisplayedEcho"))
        self.horizontalLayout.addWidget(self.lblDisplayedEcho)
        self.spnEcho = QtGui.QSpinBox(self.tab)
        self.spnEcho.setMaximum(1)
        self.spnEcho.setObjectName(_fromUtf8("spnEcho"))
        self.horizontalLayout.addWidget(self.spnEcho)
        self.lblEchoTime = QtGui.QLabel(self.tab)
        self.lblEchoTime.setText(_fromUtf8(""))
        self.lblEchoTime.setObjectName(_fromUtf8("lblEchoTime"))
        self.horizontalLayout.addWidget(self.lblEchoTime)
        self.chkDoFT = QtGui.QCheckBox(self.tab)
        self.chkDoFT.setObjectName(_fromUtf8("chkDoFT"))
        self.horizontalLayout.addWidget(self.chkDoFT)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblRangeLeft = QtGui.QLabel(self.tab)
        self.lblRangeLeft.setObjectName(_fromUtf8("lblRangeLeft"))
        self.horizontalLayout.addWidget(self.lblRangeLeft)
        self.spnRangeLeft = QtGui.QSpinBox(self.tab)
        self.spnRangeLeft.setObjectName(_fromUtf8("spnRangeLeft"))
        self.horizontalLayout.addWidget(self.spnRangeLeft)
        self.spnRangeRight = QtGui.QSpinBox(self.tab)
        self.spnRangeRight.setObjectName(_fromUtf8("spnRangeRight"))
        self.horizontalLayout.addWidget(self.spnRangeRight)
        self.btnDoIntegrate = QtGui.QPushButton(self.tab)
        self.btnDoIntegrate.setObjectName(_fromUtf8("btnDoIntegrate"))
        self.horizontalLayout.addWidget(self.btnDoIntegrate)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.plot1Nav = QtGui.QWidget(self.tab)
        self.plot1Nav.setObjectName(_fromUtf8("plot1Nav"))
        self.verticalLayout_3.addWidget(self.plot1Nav)
        self.canvas1 = QtGui.QWidget(self.tab)
        self.canvas1.setObjectName(_fromUtf8("canvas1"))
        self.verticalLayout_3.addWidget(self.canvas1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cmbT2Fit = QtGui.QComboBox(self.tab)
        self.cmbT2Fit.setObjectName(_fromUtf8("cmbT2Fit"))
        self.horizontalLayout_3.addWidget(self.cmbT2Fit)
        self.btnDoT2fit = QtGui.QPushButton(self.tab)
        self.btnDoT2fit.setObjectName(_fromUtf8("btnDoT2fit"))
        self.horizontalLayout_3.addWidget(self.btnDoT2fit)
        self.chkShowFits = QtGui.QCheckBox(self.tab)
        self.chkShowFits.setObjectName(_fromUtf8("chkShowFits"))
        self.horizontalLayout_3.addWidget(self.chkShowFits)
        self.chkPlotAllEchoes = QtGui.QCheckBox(self.tab)
        self.chkPlotAllEchoes.setObjectName(_fromUtf8("chkPlotAllEchoes"))
        self.horizontalLayout_3.addWidget(self.chkPlotAllEchoes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.t3_vlayout = QtGui.QVBoxLayout()
        self.t3_vlayout.setObjectName(_fromUtf8("t3_vlayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkRxP1 = QtGui.QCheckBox(self.tab_3)
        self.chkRxP1.setObjectName(_fromUtf8("chkRxP1"))
        self.gridLayout_2.addWidget(self.chkRxP1, 2, 0, 1, 1)
        self.chkRxP0 = QtGui.QCheckBox(self.tab_3)
        self.chkRxP0.setChecked(True)
        self.chkRxP0.setObjectName(_fromUtf8("chkRxP0"))
        self.gridLayout_2.addWidget(self.chkRxP0, 1, 0, 1, 1)
        self.txtRxP1 = QtGui.QLineEdit(self.tab_3)
        self.txtRxP1.setEnabled(False)
        self.txtRxP1.setObjectName(_fromUtf8("txtRxP1"))
        self.gridLayout_2.addWidget(self.txtRxP1, 2, 1, 1, 1)
        self.txtRxP2 = QtGui.QLineEdit(self.tab_3)
        self.txtRxP2.setEnabled(False)
        self.txtRxP2.setObjectName(_fromUtf8("txtRxP2"))
        self.gridLayout_2.addWidget(self.txtRxP2, 3, 1, 1, 1)
        self.txtRxP0 = QtGui.QLineEdit(self.tab_3)
        self.txtRxP0.setEnabled(True)
        self.txtRxP0.setObjectName(_fromUtf8("txtRxP0"))
        self.gridLayout_2.addWidget(self.txtRxP0, 1, 1, 1, 1)
        self.lblRxFitOptions = QtGui.QLabel(self.tab_3)
        self.lblRxFitOptions.setObjectName(_fromUtf8("lblRxFitOptions"))
        self.gridLayout_2.addWidget(self.lblRxFitOptions, 0, 0, 1, 1)
        self.chkRxP2 = QtGui.QCheckBox(self.tab_3)
        self.chkRxP2.setObjectName(_fromUtf8("chkRxP2"))
        self.gridLayout_2.addWidget(self.chkRxP2, 3, 0, 1, 1)
        self.txtRxP3 = QtGui.QLineEdit(self.tab_3)
        self.txtRxP3.setEnabled(False)
        self.txtRxP3.setObjectName(_fromUtf8("txtRxP3"))
        self.gridLayout_2.addWidget(self.txtRxP3, 4, 1, 1, 1)
        self.chkRxP3 = QtGui.QCheckBox(self.tab_3)
        self.chkRxP3.setText(_fromUtf8(""))
        self.chkRxP3.setObjectName(_fromUtf8("chkRxP3"))
        self.gridLayout_2.addWidget(self.chkRxP3, 4, 0, 1, 1)
        self.chkPlotRelaxivity = QtGui.QCheckBox(self.tab_3)
        self.chkPlotRelaxivity.setObjectName(_fromUtf8("chkPlotRelaxivity"))
        self.gridLayout_2.addWidget(self.chkPlotRelaxivity, 0, 2, 1, 1)
        self.btnDoRelaxFit = QtGui.QPushButton(self.tab_3)
        self.btnDoRelaxFit.setObjectName(_fromUtf8("btnDoRelaxFit"))
        self.gridLayout_2.addWidget(self.btnDoRelaxFit, 4, 2, 1, 1)
        self.cmbRelaxFitType = QtGui.QComboBox(self.tab_3)
        self.cmbRelaxFitType.setObjectName(_fromUtf8("cmbRelaxFitType"))
        self.gridLayout_2.addWidget(self.cmbRelaxFitType, 0, 1, 1, 1)
        self.chkHoldRelaxationGraph = QtGui.QCheckBox(self.tab_3)
        self.chkHoldRelaxationGraph.setObjectName(_fromUtf8("chkHoldRelaxationGraph"))
        self.gridLayout_2.addWidget(self.chkHoldRelaxationGraph, 3, 2, 1, 1)
        self.chkUseFitError = QtGui.QCheckBox(self.tab_3)
        self.chkUseFitError.setObjectName(_fromUtf8("chkUseFitError"))
        self.chkUseFitError.setChecked(True)
        self.gridLayout_2.addWidget(self.chkUseFitError, 2, 2, 1, 1)
        self.t3_vlayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.t3_vlayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.txtFitResults = QtGui.QTextEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(12)
        font.setItalic(False)
        self.txtFitResults.setFont(font)
        self.txtFitResults.setAcceptRichText(False)
        self.txtFitResults.setObjectName(_fromUtf8("txtFitResults"))
        self.verticalLayout_5.addWidget(self.txtFitResults)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionOpen_mat = QtGui.QAction(mainWindow)
        self.actionOpen_mat.setObjectName(_fromUtf8("actionOpen_mat"))
        self.actionOpen_folder = QtGui.QAction(mainWindow)
        self.actionOpen_folder.setEnabled(False)
        self.actionOpen_folder.setObjectName(_fromUtf8("actionOpen_folder"))
        self.actionQuit = QtGui.QAction(mainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpen_Decay_mat = QtGui.QAction(mainWindow)
        self.actionOpen_Decay_mat.setObjectName(_fromUtf8("actionOpen_Decay_mat"))
        self.actionSave_Decay_mat = QtGui.QAction(mainWindow)
        self.actionSave_Decay_mat.setObjectName(_fromUtf8("actionSave_Decay_mat"))
        self.menuMenu.addAction(self.actionOpen_mat)
        self.menuMenu.addAction(self.actionOpen_folder)
        self.menuMenu.addAction(self.actionOpen_Decay_mat)
        self.menuMenu.addAction(self.actionSave_Decay_mat)
        self.menuMenu.addAction(self.actionQuit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.chkRxP0, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtRxP0.setEnabled)
        QtCore.QObject.connect(self.chkRxP1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtRxP1.setEnabled)
        QtCore.QObject.connect(self.chkRxP2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtRxP2.setEnabled)
        QtCore.QObject.connect(self.chkRxP3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtRxP3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "processCPMG-vt", None))
        self.lblDisplayedEcho.setText(_translate("mainWindow", "Selected Echo Time: ", None))
        self.chkDoFT.setText(_translate("mainWindow", "Fourier", None))
        self.lblRangeLeft.setText(_translate("mainWindow", "Integration Limits", None))
        self.btnDoIntegrate.setText(_translate("mainWindow", "Integrate", None))
        self.btnDoT2fit.setText(_translate("mainWindow", "T2fit", None))
        self.chkShowFits.setText(_translate("mainWindow", "Show fits", None))
        self.chkPlotAllEchoes.setText(_translate("mainWindow", "Show all Echoes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Echo processing", None))
        self.chkRxP1.setText(_translate("mainWindow", "R0", None))
        self.chkRxP0.setText(_translate("mainWindow", "Exchange Time (s)", None))
        self.lblRxFitOptions.setText(_translate("mainWindow", "<html><head/><body><p>Relaxation Fit Options</p><p>Ticked values are fixed for fitting</p></body></html>", None))
        self.chkRxP2.setText(_translate("mainWindow", "K0", None))
        self.chkPlotRelaxivity.setText(_translate("mainWindow", "Plot Relaxivity", None))
        self.btnDoRelaxFit.setText(_translate("mainWindow", "Fit", None))
        self.chkHoldRelaxationGraph.setText(_translate("mainWindow", "Hold graph", None))
        self.chkUseFitError.setText(_translate("mainWindow", "Use R2 Error", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "Echotime / Relaxation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Fit results", None))
        self.menuMenu.setTitle(_translate("mainWindow", "Menu", None))
        self.actionOpen_mat.setText(_translate("mainWindow", "Open Echo .mat", None))
        self.actionOpen_folder.setText(_translate("mainWindow", "Open folder", None))
        self.actionQuit.setText(_translate("mainWindow", "Quit", None))
        self.actionOpen_Decay_mat.setText(_translate("mainWindow", "Open Decay .mat", None))
        self.actionSave_Decay_mat.setText(_translate("mainWindow", "Save Decay .mat", None))

